asr_listener:
  ros__parameters:
    sound_device: "M12i Mobile"
    train_voice: false
    train_voice_name: 'unknow'
# m_service:
#   ros__parameters:
#     serial_device: "/dev/ttyACM"
riva_asr:
  ros__parameters:
    sound_device: "respeaker"
    


